title: Jemima M. Tabeart
author: Jemima Tabeart
email: jemima.tabeart@ed.ac.uk
description: >
  Researcher in numerical linear algebra and data assimilation.
  
# social links
twitter_username: jemimatabeart
github_username: JemimaT

show_excerpts: true
theme: jekyll-theme-slate
