title: Jemima M. Tabeart
author: Jemima Tabeart
email: jemima.tabeart@ed.ac.uk
description: >
  Professional website for Dr Jemima M. Tabeart
  
# social links
twitter_username: jemimatabeart
github_username: JemimaT

theme: jekyll-theme-slate
